### ISSUE TITLE
Provide badge snippets for several markup languages

### ISSUE THREAD

**Issue by splattael** [rrrene/inch-pages#6]
Example CodeClimate:
- https://codeclimate.com/github/rrrene/inch
- click on the badge at top right
- https://codeclimate.com/github/rrrene/inch/badges

Example Travis CI:
- https://travis-ci.org/rrrene/inch
- click on the badge at top right

I like Travis' solution.

It would be nice having this on Inch Pages when clicking on the badge:
http://inch-pages.github.io/github/rrrene/inch/

**Comment by rrrene** [comment]
Thought of that as well. I put it in the TODOS file: rrrene/inch-pages@2b59676

Also added your suggestion of providing a "popular repos using this" section to the homepage.

**Comment by rrrene** [comment]
Done.
