### ISSUE TITLE
Markdown processes repo name

### ISSUE THREAD

**Issue by hemflit** [rrrene/inch-pages#88]
`/_includes/repo/explanation.md` leaves an unescaped `{{ page.repo.name }}` to be processed by markdown. Any underscores in the name get treated as emphasis marks.

Example: http://inch-pages.github.io/github/watu/random_unique_id/

**Comment by rrrene** [comment]
[Fixed](https://github.com/rrrene/inch-pages/commit/0aea900f7ac6805a765a2424956259650356dffd). Thanks for the heads up!

Have you seen http://inch-ci.org (the successor to Inch Pages)?

**Comment by hemflit** [comment]
Nope, hadn't seen inch-ci before. Looks awesome, thanks!
