### ISSUE TITLE
Allow http or https at the URL on initial Page

### ISSUE THREAD

**Issue by marceloboeira** [rrrene/inch-pages#93]
It doens't works with http, only https. :disappointed:

**Comment by rrrene** [comment]
I could write a patch for this, but aren't all GitHub-URLs always using `https`?

**Comment by marceloboeira** [comment]
yeap, but you should make available to use, user/repo instead of the whole url, that would be awesome...

**Comment by rrrene** [comment]
My thought was just that username/repo would have to be typed in, whereas the GitHub URL can be easily copy-pasted from the browser ... 

But I created a ticket in the Inch CI project (see above). Thanks for your feedback!

**Comment by marceloboeira** [comment]
@rrrene thank you for the attention. :)
